version: 2

# Настройки компиляции
builds:
  - env:
      - CGO_ENABLED=0 # Отключаем CGO для максимальной переносимости бинарников
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Передаем те самые флаги оптимизации, о которых шла речь в BUILDING.md, 
    # чтобы файлы весили на 40% меньше
    ldflags:
      - -s -w

# В каком виде упаковать файлы (zip для Windows, tar.gz для Linux/macOS)
archives:
  - formats:
      windows: zip
      linux: tar.gz
      darwin: tar.gz