version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

# ИСПРАВЛЕННЫЙ БЛОК ARCHIVES
archives:
  - formats: ["tar.gz"]
    # Накатываем исключение: для Windows упаковываем в .zip вместо .tar.gz
    format_overrides:
      - goos: windows
        formats: ["zip"]