name: Release

on:
  push:
    tags:
      - 'v*' # Сценарий сработает только тогда, когда ты вешаешь тег версии (например, v1.0.0)

permissions:
  contents: write # Даем роботу права на запись, чтобы он мог прикрепить файлы к релизу

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Важно для корректной работы подсчета версий

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      # Запуск сборщика, который скомпилирует всё по нашему конфигу
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Автоматический токен GitHub
